[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "credit_card_default_mlops"
version = "0.0.1"
description = "Pr\u00e9diction du d\u00e9faut de paiement de cartes de cr\u00e9dit - Pipeline MLOps complet"
authors = [
  { name = "Singapinda Zagre" },
]
license = { file = "LICENSE" }
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License"
]
requires-python = "~=3.10.0"


[tool.ruff]
line-length = 99
src = ["credit_card_default_mlops"]
include = ["pyproject.toml", "credit_card_default_mlops/**/*.py"]

[tool.ruff.lint]
extend-select = ["I"]  # Add import sorting

[tool.ruff.lint.isort]
known-first-party = ["credit_card_default_mlops"]
force-sort-within-sections = true

